groups:
  - name: my-alerts
    rules:
    - alert: NodeExporterDown
      expr: up{job="prometheus-node-exporter"} != 1
      for: 1m
      labels:
        severity: critical
        team: support
      annotations:
        summary: Server not ready

    - alert: ClusterNodeMasterNotReady 
      expr: kube_node_status_condition{condition="Ready", node="pi-master", status="true"} != 1
      for: 1m
      labels:
        severity: critical
        team: support
      annotations:
        summary: Node master k3s not ready 

    - alert: ClusterNode01NotReady 
      expr: kube_node_status_condition{condition="Ready", node="pi-node01", status="true"} != 1
      for: 1m
      labels:
        severity: warning
        team: on-call
      annotations:
        summary: Node worker 1 k3s not ready 

    - alert: ClusterNode02NotReady 
      expr: kube_node_status_condition{condition="Ready", node="pi-node02", status="true"} != 1
      for: 1m
      labels:
        severity: warning
        team: on-call
      annotations:
        summary: Node worker 2 k3s not ready 
