groups:
  - name: my-alerts
    rules:
    - alert: NodeExporterDown
      expr: up{job="prometheus-node-exporter"} != 1
      for: 1m
      labels:
        severity: critical
        team: support
      annotations:
        summary: Server not ready

    - alert: NodesNotReady 
      expr:  job:clusterK3sUp == 0 or job:nodesDown != 0
      for: 1m
      labels:
        severity: critical
        team: support
      annotations:
        summary: One of the nodes is not ready

    - alert: AppsNotReady
      expr: job:clusterK3sUp == 0 or job:deploymentsDown != 0 or job:podsDown !=0
      for: 1m
      labels:
        severity: warning
        team: on-call
      annotations:
        summary: One of the apps is not ready
