groups:
  - name: my-rules
    rules:
    - record: job:free_memory_percent
      expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

    - record: job:node_cpu
      expr: avg without(cpu) (rate(node_cpu_seconds_total{mode="idle"}[5m]))

    - record: job:clusterK3sUp
      expr: up{instance="pi-master:8080", job="kube-state-metrics"}
