groups:
  - name: my-rules
    rules:
    - record: job:free_memory_percent
      expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

    - record: job:node_cpu
      expr: avg without(cpu) (rate(node_cpu_seconds_total{mode="idle"}[5m]))

    - record: job:clusterK3sUp
      expr: up{instance="pi-master:8080", job="kube-state-metrics"}

    - record: job:nodesDown
      expr: sum(kube_node_status_condition{condition="Ready", status="unknown"}) > 0 or sum(kube_node_status_condition{condition="Ready", status="false"}) > 0

    - record: job:deploymentsDown
      expr: sum(kube_deployment_status_condition{namespace="yotflix", condition="Available", status="false"}) > 0

    - record: job:podsDown
      expr: sum(kube_pod_status_scheduled{namespace="yotflix", condition="false"}) > 0
