apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app:  deluge
  name: deluge-pvc-config
  namespace: yotflix
spec:
  storageClassName: ""
  volumeName: deluge-pv-config  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
status: {}
