apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
  name: deluge-dpl
  namespace: yotflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 8.8.8.8
        options:
        - name: ndots
          value: "5"
        searches:
        - yotflix.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      containers:
        - env:
            - name: DELUGE_LOGLEVEL
              value: error
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/deluge:latest
          name: deluge
          ports:
            - containerPort: 8112
            - containerPort: 6881
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: deluge-config
            - mountPath: /downloads
              name: deluge-downloads
            - mountPath: /watch
              name: deluge-watch
      restartPolicy: Always
      volumes:
        - name: deluge-config
          persistentVolumeClaim:
            claimName: deluge-pvc-config
        - name: deluge-downloads
          persistentVolumeClaim:
            claimName: jellyfin-pvc-media
        - name: deluge-watch
          persistentVolumeClaim:
            claimName: jackett-pvc-blackhole
