version: "3.5"
services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /opt/bitnami/prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
