version: "3.8"
services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /opt/bitnami/prometheus/conf:/opt/bitnami/prometheus/conf
    restart: unless-stopped

  alertmanager:
    image: bitnami/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
      - 5001:5001
    volumes:
      - /opt/bitnami/alertmanager/conf/config.yml:/opt/bitnami/alertmanager/conf/config.yml
    depends_on: 
      - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - "/opt/grafana/conf/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "/opt/grafana/conf/dashboards:/etc/grafana/provisioning/dashboards:rw"
    restart: unless-stopped
    depends_on: 
      - prometheus
