route:
  receiver: admin
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1d

receivers:
- name: admin
  email_configs:
  - to: "yg.herve@gmail.com"
    from: "yg.herve@gmail.com"
    smarthost: smtp.gmail.com:587
    auth_username: "yg.herve@gmail.com"
    auth_identity: "yg.herve@gmail.com"
    $AUTH_PASSWORD
  discord_configs:
  - $WEBHOOK_URL
