route:
  receiver: admin
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1d
  routes:
    - matchers:
        - team=~"support|on-call"
      receiver: email
      continue: true
    - matchers:
        - team="on-call"
      receiver: discord

receivers:
- name: admin
  email_configs:
  - to: "yg.herve@gmail.com"
    from: "yg.herve@gmail.com"
    smarthost: smtp.gmail.com:587
    auth_username: "yg.herve@gmail.com"
    auth_identity: "yg.herve@gmail.com"
    $AUTH_PASSWORD
  discord_configs:
  - $WEBHOOK_URL
- name: email
  email_configs:
  - to: "yg.herve@gmail.com"
    from: "yg.herve@gmail.com"
    smarthost: smtp.gmail.com:587
    auth_username: "yg.herve@gmail.com"
    auth_identity: "yg.herve@gmail.com"
    $AUTH_PASSWORD
- name: discord
  discord_configs:
  - $WEBHOOK_URL
