apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellyfin
  name: jellyfin-pvc-config
  namespace: yotflix
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
status: {}
