apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-pv-blackhole
  labels:
    app: jackett
spec:
  storageClassName: ""
  claimRef:
    name: jackett-pvc-blackhole
    namespace: yotflix  
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jackett/blackhole"
