apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-pv-config
  labels:
    app: deluge
spec:
  storageClassName: ""
  claimRef:
    name: deluge-pvc-config
    namespace: yotflix  
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/deluge/config"
