- name: monitoring
  hosts: server1
  vars_files:
    - secrets.yml
  tasks:
    - name: Ensure directory exists for prometheus conf
      become: yes
      ansible.builtin.file:
        path: /opt/bitnami/prometheus/conf/rules
        state: directory
        mode: '0755'
        recurse: yes
        owner: pi
        group: pi

    - name: Copy prometheus config files
      ansible.builtin.copy:
        src: ./prometheus/
        dest: /opt/bitnami/prometheus/conf/
        force: true
        mode: '0644'
        owner: pi
        group: pi

    - name: Ensure directory exists for alertmanager conf
      become: yes
      ansible.builtin.file:
        path: /opt/bitnami/alertmanager/conf
        state: directory
        mode: '0755'
        recurse: yes
        owner: pi
        group: pi

    - name: Copy alertmanager config files
      ansible.builtin.copy:
        src: ./alertmanager/
        dest: /opt/bitnami/alertmanager/conf/
        force: true
        mode: '0644'
        owner: pi
        group: pi

    - name: Ensure directory exists for grafana conf
      become: yes
      ansible.builtin.file:
        path: /opt/grafana/conf/
        state: directory
        mode: '0755'
        recurse: yes
        owner: pi
        group: pi

    - name: Copy grafana config files
      ansible.builtin.copy:
        src: ./grafana/
        dest: /opt/grafana/conf/
        force: true
        mode: '0644'
        owner: pi
        group: pi

    - name: Ensure directory exists for docker conf
      become: yes
      ansible.builtin.file:
        path: /opt/docker/conf/
        state: directory
        mode: '0755'
        recurse: yes
        owner: pi
        group: pi
