- name: deploy docker compose
  hosts: pi-server1
  vars_files:
    - secrets.yml
  tasks:
    - name: get packages fact
      package_facts:
        manager: auto

    - name: Install docker
      include_role: 
        name: install-docker
      when: "'docker-compose-plugin' not in ansible_facts.packages"

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../../docker/monitoring/
        dest: /opt/docker/conf/
        mode: '0644'
        owner: pi
        group: pi

    - name: Stop and remove services (docker compose down)
      command: docker compose -f /opt/docker/conf/docker-compose.yml down

    - name: Start services (docker compose up)
      command: docker compose -f /opt/docker/conf/docker-compose.yml up -d
