- name: deploy docker compose
  hosts: pi-server1
  vars_files:
    - secrets.yml
  tasks:
    - name: Ensure docker compose is present
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present

    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: ../../docker/monitoring/
        dest: /opt/docker/conf/
        mode: '0644'
        owner: pi
        group: pi

    - name: Stop and remove services (docker compose down)
      command: docker compose -f /opt/docker/conf/docker-compose.yml down

    - name: Start services (docker compose up)
      command: docker compose -f /opt/docker/conf/docker-compose.yml up -d
