apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellyfin
  name: jellyfin-pvc-media2
  namespace: yotflix
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-media2  
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
