apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-media
  labels:
    app: jellyfin
spec:
  storageClassName: ""
  claimRef:
    name: jellyfin-pvc-media
    namespace: yotflix  
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/media"
