apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv-media2
  labels:
    app: jellyfin
spec:
  storageClassName: ""
  claimRef:
    name: jellyfin-pvc-media2
    namespace: yotflix  
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/media2"
