apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellyfin
  name: jellyfin-pvc-media
  namespace: yotflix
spec:
  storageClassName: ""
  volumeName: jellyfin-pv-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
status: {}
