apiVersion: v1
kind: Service
metadata:
  labels:
    app: jackett
  name: jackett-svc
  namespace: yotflix
spec:
  type: LoadBalancer
  ports:
    - name: "9117"
      port: 9117
      targetPort: 9117
  selector:
    app: jackett
status:
  loadBalancer: {}
